apiVersion: 1

datasources:
  - name: IoTInfluxDB
    uid: iot-influxdb
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: iot
    secureJsonData:
      token: myinfluxtoken123456
