apiVersion: 1

datasources:
  - name: FinanceMSSQL
    uid: finance-mssql
    type: mssql
    url: mssql:1433
    user: sa
    secureJsonData:
      password: "FinanceStr0ng!"
    jsonData:
      database: financedb
      encrypt: disable
