apiVersion: 1

datasources:
  - name: SaaSDB
    type: mysql
    url: mysql:3306
    user: grafana
    secureJsonData:
      password: grafanapass
    jsonData:
      database: saasdb
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
