apiVersion: 1

datasources:
  - name: HRPostgres
    uid: hr-postgres
    type: postgres
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: grafanapass
    jsonData:
      database: hrdb
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
